# Generated by Django 6.0.2 on 2026-02-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='food_type',
            field=models.CharField(choices=[('veg', 'Veg'), ('nonveg', 'Non Veg')], default='veg', max_length=10),
        ),
    ]
