# Generated by Django 6.0.2 on 2026-02-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_discount_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
